## Assignment 2: Lexical Scoping

@Esther Ling

29 May 2018

In [2]:
## Load the functions
source("cacheMatrix.R")

## Testing the functions

In [16]:
mat <- matrix(1:4,2,2)
aMatrix <- makeCacheMatrix(mat)

In [17]:
aMatrix$get()

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [18]:
aMatrix$getinverse() # NULL

NULL

In [19]:
cacheSolve(aMatrix)
solve(mat) # cross-check answer with solve()
aMatrix$getinverse() # we retrieve the inverse from the cache

[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

## Now when we change the matrix using set(), we need to re-compute the inverse

In [21]:
mat <- matrix(5:8,2,2)
aMatrix$set(mat)
aMatrix$getinverse() # NULL: need to recompute the inverse

NULL

In [22]:
cacheSolve(aMatrix)
aMatrix$getinverse()
solve(mat)

[,1] [,2]
[1,] -4    3.5
[2,]  3   -2.5

[,1] [,2]
[1,] -4    3.5
[2,]  3   -2.5

[,1] [,2]
[1,] -4    3.5
[2,]  3   -2.5